#
# txtai Material for MkDocs configuration
#

site_name: txtai
repo_name: neuml/txtai
repo_url: https://github.com/neuml/txtai
copyright: © NeuML LLC, Apache-2.0 License
theme:
    name: material
    logo: images/logo.png
    favicon: images/logo.png
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: blue
        accent: blue
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                rendering:
                    show_root_full_path: false
                    show_root_heading: true
                    show_root_toc_entry: false
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
nav:
    - Home: index.md
    - Why txtai?: why.md
    - Installation: install.md
    - Examples: examples.md
    - Embeddings: embeddings.md
    - Pipelines:
        - Overview: pipelines/overview.md
        - Extractor: pipelines/extractor.md
        - Labels: pipelines/labels.md
        - ONNX: pipelines/onnx.md
        - Segmentation: pipelines/segmentation.md
        - Similarity: pipelines/similarity.md
        - Summary: pipelines/summary.md
        - Textractor: pipelines/textractor.md
        - Trainer: pipelines/trainer.md
        - Transcription: pipelines/transcription.md
        - Translation: pipelines/translation.md
    - Workflows: workflows.md
    - API: api.md
