name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install mkdocs-material==7.3.0 mkdocstrings==0.16.1 git+https://github.com/neuml/txtai#egg=txtai[all]
      - run: mkdocs gh-deploy --force
 